name: trace-20240826-z1
channels:
  - conda-forge
  - bioconda
  - gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - alsa-lib=1.2.12
  - amply=0.1.6
  - anyio=4.4.0
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - argparse-dataclass=2.0.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attmap=0.13.2
  - attrs=24.2.0
  - aws-c-auth=0.7.25
  - aws-c-cal=0.7.3
  - aws-c-common=0.9.25
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.7
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.4
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.5
  - aws-sdk-cpp=1.11.379
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.8.0
  - bleach=6.1.0
  - blosc=1.21.6
  - bokeh=3.4.2
  - bottleneck=1.4.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.0
  - c-blosc2=2.15.1
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cads-api-client=1.2.0
  - cairo=1.18.0
  - cartopy=0.23.0
  - cdsapi=0.7.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - cfgv=3.3.1
  - cfitsio=4.4.1
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - coin-or-cbc=2.10.11
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.11
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - conda-inject=1.3.2
  - configargparse=1.7
  - connection_pool=0.0.3
  - contourpy=1.2.1
  - curl=8.9.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - datashader=0.16.3
  - datrie=0.8.2
  - dbus=1.13.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - distlib=0.3.8
  - distributed=2024.8.0
  - docutils=0.21.2
  - double-conversion=3.3.0
  - dpath=2.2.0
  - eido=0.2.2
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - filelock=3.15.4
  - fiona=1.9.6
  - firefox=129.0.1
  - fmt=11.0.2
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.6.1
  - gdal=3.9.1
  - geckodriver=0.35.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.12.2
  - geotiff=1.7.3
  - geoviews=1.12.0
  - geoviews-core=1.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - graphite2=1.3.13
  - gurobi=11.0.3
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - holoviews=1.19.1
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - humanfriendly=10.0
  - hvplot=0.10.0
  - hyperframe=6.0.1
  - icu=75.1
  - identify=2.6.0
  - idna=3.7
  - immutables=0.20
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.2
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.17
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgdal=3.9.1
  - libgdal-core=3.9.1
  - libgdal-fits=3.9.1
  - libgdal-grib=3.9.1
  - libgdal-hdf4=3.9.1
  - libgdal-hdf5=3.9.1
  - libgdal-jp2openjpeg=3.9.1
  - libgdal-kea=3.9.1
  - libgdal-netcdf=3.9.1
  - libgdal-pdf=3.9.1
  - libgdal-pg=3.9.1
  - libgdal-postgisraster=3.9.1
  - libgdal-tiledb=3.9.1
  - libgdal-xls=3.9.1
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgomp=14.1.0
  - libgoogle-cloud=2.28.0
  - libgoogle-cloud-storage=2.28.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm18=18.1.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.20.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - linopy=0.3.14
  - llvmlite=0.43.0
  - locket=1.0.0
  - logmuse=0.2.6
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.1
  - mdurl=0.1.2
  - minizip=4.0.7
  - mistune=3.0.2
  - msgpack-python=1.0.8
  - multipledispatch=0.6.0
  - multiurl=0.3.1
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.1
  - networkx=3.3
  - nodeenv=1.9.1
  - nomkl=1.0
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.103
  - numba=0.60.0
  - numexpr=2.10.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.3.1
  - orc=2.0.1
  - outcome=1.3.0.post0
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0
  - panel=1.4.5
  - param=2.1.1
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.44
  - peppy=0.40.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - polars=1.5.0
  - poppler=24.08.0
  - poppler-data=0.4.12
  - postgresql=16.4
  - pre-commit=3.8.0
  - proj=9.4.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.8.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycountry=24.6.1
  - pycparser=2.22
  - pyct=0.5.0
  - pygments=2.18.0
  - pyogrio=0.9.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pypsa=0.29.0
  - pyshp=2.3.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - pytables=3.9.2
  - pytest=8.3.2
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyviz_comms=3.0.3
  - pyyaml=6.0.2
  - pyzmq=26.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - rasterio=1.3.10
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - reretry=0.11.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - richdem=2.3.0
  - rioxarray=0.17.0
  - rpds-py=0.20.0
  - s2n=1.5.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - selenium=4.23.1
  - selenium-manager=4.23.0
  - send2trash=1.8.3
  - setuptools=72.1.0
  - shapely=2.0.5
  - six=1.16.0
  - slack-sdk=3.31.0
  - slack_sdk=3.31.0
  - smart_open=7.0.4
  - smmap=5.0.0
  - snakefmt=0.10.2
  - snakemake=8.16.0
  - snakemake-interface-common=1.17.3
  - snakemake-interface-executor-plugins=9.2.0
  - snakemake-interface-report-plugins=1.0.0
  - snakemake-interface-storage-plugins=3.2.4
  - snakemake-minimal=8.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spdlog=1.14.1
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - stopit=1.1.2
  - tabulate=0.9.0
  - tblib=3.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - throttler=1.2.2
  - tiledb=2.25.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - toposort=1.10
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - trio=0.26.2
  - trio-websocket=0.11.1
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - ubiquerg=0.8.0
  - uc-micro-py=1.0.3
  - ukkonen=1.0.1
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.2
  - validators=0.33.0
  - veracitools=0.1.3
  - virtualenv=20.26.3
  - wayland=1.23.0
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - wrapt=1.16.0
  - wsproto=1.2.0
  - xarray=2024.7.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - yte=1.5.4
  - zeromq=4.3.5
  - zict=3.0.0
  - zip=3.0
  - zipp=3.20.0
  - zlib=1.3.1
  - zlib-ng=2.2.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - atlite==0.2.14.dev15+gbb568a7
      - geojson==3.1.0
      - haversine==2.8.1
      - oauthlib==3.2.2
      - progressbar2==4.4.2
      - python-utils==3.8.2
      - requests-oauthlib==1.3.1
      - searoute==1.4.2
      - snakemake-executor-plugin-cluster-generic==1.0.9
      - snakemake-executor-plugin-slurm==0.9.0
      - snakemake-executor-plugin-slurm-jobstep==0.2.1
      - snakemake-storage-plugin-http==0.2.3
