name: trace
channels:
- conda-forge
- gurobi
- bioconda
dependencies:
- python
- ipython
- ipykernel

  # Managing data
- xarray
- dask
- pandas
- geopandas>=1
- geoviews
- numpy
- gdal
- zip
- requests
- curl
- openpyxl

  # Visualisation
- matplotlib
- seaborn
- hvplot

# AUX for bokeh plot export
- selenium
- firefox
- geckodriver

  # Modelling framework
- pycountry
- pypsa<0.29 # until n.optimize() is used

  # Data retrieval
- cdsapi>=0.7.0

  # Auxiliary packages for atlite (explicitly required from conda-forge while it is installed via pip)
- rasterio
- fiona
- bottleneck

  # Workflow management
- snakemake>=8.5
- snakefmt
- notebook
- nbconvert

  # Read Julia files
- h5py

  # Solver
- gurobi

  # Code style and quality checks
- pre-commit

- pip

- pip:
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
  - git+https://github.com/pypsa/atlite.git@monthly-requests
  - searoute
  - haversine